[book]
authors = ["Vitalii Perehonchuk"]
language = "uk"
multilingual = false
src = "./content/files/uk"
title = "WebDoky 3"

[build]
create-missing = false

[output.html]
additional-css = ["src/style.css"]
additional-js = ["src/script.js"]
no-section-label = true

[output.html.fold]
enable = true # whether or not to enable section folding
level = 1     # the depth to start folding

[output.html.print]
enable = false

[output.html.search]
enable = false

[preprocessor.summary]
before = ["links", "rewire-paths"]
# command = "node scripts/summary/summary.js"
command = "preprocessors/summary"

[preprocessor.rewire-paths]
after = ["summary"]
# command = "node scripts/rewire-paths/rewire-paths.js"
command = "preprocessors/rewire-paths"

[preprocessor.writer]
after = ["rewire-paths", "summary", "run-macros"]
before = ["format-links"]
# before = ["summary"]
# command = "node scripts/writer/index.js"
command = "preprocessors/writer"
# command = "./redirect_to_file.zsh"

# [preprocessor.yari-ports]
# after = ["summary"]
# before = ["links", "strip-frontmatter"]
# command = "node --experimental-specifier-resolution=node scripts/yari-ports/yari-ports.js"
# enable = false

[preprocessor.strip-frontmatter]
after = ["rewire-paths", "summary", "writer"]
before = ["links"]
# command = "node scripts/strip-frontmatter/strip-frontmatter.js"
command = "preprocessors/strip-frontmatter"

[preprocessor.format-links]
after = ["rewire-paths", "summary", "run-macros"]
before = ["links"]
command = "preprocessors/format-links"

# [preprocessor.inject-authors]
# after = ["summary"]
# before = ["rewire-paths"]
# command = "preprocessors/inject-authors"

[preprocessor.run-macros]
after = ["summary"]
before = ["format-links", "links"]
command = "preprocessors/run-macros"
