name: Deploy
run-name: ${{ github.actor }} deploys 🚀
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git submodule add git@github.com:webdoky/content.git ./content
      - run: make content/files/uk/SUMMARY.md
      - name: Setup MDBook
        run: mkdir bin && curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.35/mdbook-v0.4.35-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin && bin/mdbook build
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: "go get ..."
      - run: git submodule add git@github.com:mdn/content.git ./original-content
      - run: git submodule add git@github.com:webdoky/interactive-examples.git
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: cd interactive-examples && yarn install
      - run: cd interactive-examples && yarn build
      - run: make book/uk
      - run: make book
