name: Deploy
run-name: ${{ github.actor }} deploys 🚀
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup MDBook
        run: mkdir bin && curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.35/mdbook-v0.4.35-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: "go get ..."
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: cd interactive-examples && yarn install
      - run: cd interactive-examples && yarn build
      - run: PATH=$PATH:bin make book/uk
      - run: make book
